### ISSUE TITLE
 link does not appear

### ISSUE THREAD

**Issue by Dmalizer** [nolanaatama/sd-1click-colab-temp#3]
I have this problem, the stable diffusion link does not appear.
![no ap](https://user-images.githubusercontent.com/121835795/210287023-bf9e82a3-ec10-41b8-81fb-5c5d62139b0a.PNG)

**Comment by nolanaatama** [comment]
please download the file from this repo for the fix:
https://github.com/nolanaatama/sd-1click-colab

**Comment by Dmalizer** [comment]
> please download the file from this repo for the fix: https://github.com/nolanaatama/sd-1click-colab

Thanks a lot.
